language: node_js
node_js:
  - "9"
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
install:
  - cd functions && npm install
before_script:
  - npm install -g firebase-tools
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --project prod --token $FIREBASE_TOKEN; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then firebase deploy --project qa --token $FIREBASE_TOKEN; fi
notifications:
  email:
    on_failure: change
    on_success: change
